[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sputnik"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
  "requests>=2.0",
  "PyYAML>=6.0"
]
